area/main-binary:
  - 'main.go'
  - 'internal/**/*'
area/sdk:
  - any:
    - 'pkg/**/*'
    - '!pkg/plugins/**/*'
area/plugin:
  - 'pkg/plugins/**/*'
area/infra:
  - '.gitignore'
  - '.github/**/*'
  - '.goreleaser.yml'
  - '.golangci.yml'
  - 'tools/scripts/**/*'
  - 'Makefile'
  - 'Dockerfile'
area/deps:
  - 'go.mod'
  - 'go.sum'
area/docs:
  - '**/*.md'
  - 'LICENSE'
area/testing:
  - '**/*_test.go'
  - '**/testdata/**/*'
area/sample:
  - 'example/**/*'
